### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by BB9z** [BB9z/iOS-Project-Template#1]
- [x] 素材更新
- [x] Color.swift 废弃
- [ ] uilabel+app，resize label 提出到 app kit
- [x] UIPickerView+app 提出到 RFKit
- [ ] UITableView+app 提出到 RFKit?
- [ ] UITextField+app 提出到 RFKit
- [x] 业务关联紧密的 category 清理
- [x] MBDebug 包装整理，不要 debug config 模式，改为 user default 存储
- [x] RFDebugger 方法提出
- [x] 项目 organization  #置空
- [x] user 对象处理
- [x] MBFormTextField 移除
- [x] table view header footer xib 给一个合理的设计状态
- [x] 移除 offscreenRendering
- [x] 移除 DebugAlert
- [x] MBDatePickerViewController.xib
- [x] MBAnalytics 清理
- [x] MBEntitiesCollectionView header
- [ ] 第一个页面 bottom bar show 未设置时的 bug
- [ ] UserLoginRequired 机制
- [ ] list datasource 提出到 app kit
- [x] view 截图提出到独立的类
- [x] setup 脚本安装依赖，确保 submodel
- [x] Common.h CommonUI.h
- [x] 导航 remove 方法提到 RFKit
- [x] 增加 swift category
- [x] MBPublishImagePicker
- [x] MBErrorCode
- [x] 更新 list data source
